[package]
name = "staking-miner"
version = "1.0.0"
authors = ["gpu <info@gpu.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
clap = { version = "4.0.9", features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
jsonrpsee = { version = "0.15.1", features = ["ws-client", "macros"] }
log = "0.4.17"
paste = "1.0.7"
serde = "1.0.137"
serde_json = "1.0"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "sync"] }
remote-externalities = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
sp-core = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
sp-version = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
sp-io = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
sp-npos-elections = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
sc-transaction-pool-api = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }

frame-system = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
frame-support = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
frame-election-provider-support = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
pallet-election-provider-multi-phase = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
pallet-staking = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
pallet-balances = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }
pallet-transaction-payment = { git = "https://github.com/brahmGAN/substrate", branch = "polkadot-v1.0.0" }

core-primitives = { package = "gpu-core-primitives", path = "../../primitives/core" }

runtime-common = { package = "gpu-runtime-common", path = "../../runtime/common" }
gpu-runtime = { path = "../../runtime/gpu" }
exitcode = "1.1"

sub-tokens = { git = "https://github.com/brahmGAN/substrate-debug-kit", branch = "master" }
signal-hook = "0.3"
futures-util = "0.3"

[dev-dependencies]
assert_cmd = "2.0.4"
